version: '3.8'
# this block denotes the services we are going to create
services:
#service 1
  app1:
    build:
      context: ./app1
    container_name: app1
    ports:
      - "3001:3001"
    networks:
      - app-network
# service 2
  app2:
    build:
      context: ./app2
    container_name: app2
    ports:
      - "3002:3002"
    networks:
      - app-network
#service 3
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - app-network
# this defines the intracontainer network - Bridge
networks:
  app-network:
    driver: bridge