name: CI/CD Multi-App Compose Deployment

on:
  push:
    branches:
      - main

env:
  IMAGE1: ${{ secrets.DOCKER_USERNAME }}/app1
  IMAGE2: ${{ secrets.DOCKER_USERNAME }}/app2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push app1
        run: |
          docker build -t $IMAGE1:latest ./app1
          docker push $IMAGE1:latest

      - name: Build & Push app2
        run: |
          docker build -t $IMAGE2:latest ./app2
          docker push $IMAGE2:latest

      - name: SSH & Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/your-project-dir
            git pull origin main
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker-compose pull
            docker-compose up -d --build